services:
  proxy:
    image: traefik:v2.12.1
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    container_name: reo-backend-v${TAG}
    build:
      context: ./
      target: backend-dev
    env_file:
      - .env
    develop:
      watch:
        - path: ./api/
          action: sync
          target: /usr/local/app/api
        - path: ./api/package.json
          action: rebuild
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: 8000

  client:
    container_name: reo-client-v${TAG}
    build:
      context: ./
      target: client-dev
    env_file:
      - .env
    develop:
      watch:
        - path: ./web/src
          action: sync
          target: /usr/local/app/src
        - path: ./web/package.json
          action: rebuild
    labels:
      traefik.http.routers.client.rule: Host(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 5050
