entryPoints:
  web:
    address: :80
    http:
      redirections: # Redirects http traffic to https
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${EMAIL_ID}
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
  insecure: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web
